name: check and push the latest alpine 

on:
  Schedule:
    - cron : "0 0 * * *"
  workflow_dispatch:

jobs:
  update-alpine:
    runs-on: ubuntu-latest

    env: 
      AWS-REGION: eu-central-1
      ECR_REPO_NAME: cedar-server               
      AWS_ACCOUNT_ID: 123456789012


    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install dependencies 
        run: |
          sudo apt-get update
          sudo apt-get install -y jq awscli

      - name: Fetch Latest Alpine version from Docker Hub
        id : get_latest_alpine    