name: Sync Node Alpine Image

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"  # Runs daily at 2 AM UTC

jobs:
  check-and-update-node-alpine:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-central-1
      ECR_REPO: my-alpine-node-image

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Fetch Latest Node Alpine Tag
        id: dockerhub
        run: |
          LATEST_TAG=$(curl -s "https://registry.hub.docker.com/v2/repositories/library/node/tags/?page_size=100" \
          | jq -r '.results[].name' \
          | grep -E '^[0-9]+(\.[0-9]+)*-alpine$' \
          | sort -Vr \
          | head -n 1)
          echo "Latest Node Alpine Tag: $LATEST_TAG"
          echo "FULL_TAG=$LATEST_TAG" >> "$GITHUB_OUTPUT"
          echo "$LATEST_TAG" > latest_tag.txt

      - name: Upload tag artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest-node-alpine-tag
          path: latest_tag.txt

      - name: Download previous tag artifact
        uses: actions/download-artifact@v4
        with:
          name: latest-node-alpine-tag
        continue-on-error: true

      - name: Read previous tag
        id: read-prev
        run: |
          if [[ -f latest_tag.txt ]]; then
            PREV_TAG=$(cat latest_tag.txt)
            echo "PREVIOUS_TAG=$PREV_TAG" >> "$GITHUB_OUTPUT"
          else
            echo "PREVIOUS_TAG=" >> "$GITHUB_OUTPUT"
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Check if ECR tag already exists
        id: check-ecr
        run: |
          set -e
          TAG=${{ steps.dockerhub.outputs.FULL_TAG }}
          IMAGE_EXISTS=$(aws ecr describe-images \
            --repository-name $ECR_REPO \
            --image-ids imageTag=$TAG \
            --region $AWS_REGION \
            --query 'imageDetails[0].imageTags[0]' \
            --output text || echo "NOT_FOUND")
          echo "ECR_IMAGE_TAG=$IMAGE_EXISTS" >> "$GITHUB_OUTPUT"

      - name: Pull, Tag, and Push to ECR (if not exists)
        if: steps.check-ecr.outputs.ECR_IMAGE_TAG == 'NOT_FOUND'
        run: |
          TAG=${{ steps.dockerhub.outputs.FULL_TAG }}
          echo "Pulling node:$TAG"
          docker pull node:$TAG
          docker tag node:$TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPO:$TAG

      - name: Notify Slack of New Push
        if: steps.check-ecr.outputs.ECR_IMAGE_TAG == 'NOT_FOUND'
        uses: slackapi/slack-github-action@v2
        with:
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          method: chat.postMessage
          payload: |
            channel: "#production-alerts"
            text: |
              "channel": "${{ secrets.SLACK_CHANNEL_NAME }}",
              "text": "✅ *Node Alpine Updated*: New version `${{ steps.dockerhub.outputs.FULL_TAG }}` has been pushed to ECR repo `${{ env.ECR_REPO }}`."

      - name: Skip Push (if already up-to-date)
        if: steps.check-ecr.outputs.ECR_IMAGE_TAG != 'NOT_FOUND'
        run: echo "Image already up-to-date in ECR. Skipping push."
