name: Check and Push Node Alpine Image

on:
  workflow_dispatch:

jobs:
  check-and-update-image:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      ECR_REPO: your-ecr-repo-name
      IMAGE_TAG: node-alpine
      LOCAL_TAG: node:alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: true
        env:
          AWS_REGION: ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Pull latest official image
        run: docker pull $LOCAL_TAG

      - name: Get current digest of official image
        id: official
        run: |
          docker inspect --format='{{index .RepoDigests 0}}' $LOCAL_TAG | cut -d'@' -f2 > official_digest.txt
          cat official_digest.txt

      - name: Try to download previous digest (optional)
        id: download-artifact
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: node-alpine-version
          path: ./

      - name: Read previous digest (if exists)
        id: compare
        run: |
          if [ -f alpine-version.txt ]; then
            echo "PREVIOUS_DIGEST=$(cat alpine-version.txt)" >> $GITHUB_ENV
          else
            echo "No previous artifact found. First run."
            echo "PREVIOUS_DIGEST=none" >> $GITHUB_ENV
          fi

      - name: Compare and push if different
        id: push-image
        run: |
          CURRENT_DIGEST=$(cat official_digest.txt)
          echo "Current: $CURRENT_DIGEST"
          echo "Previous: $PREVIOUS_DIGEST"
          
          if [ "$PREVIOUS_DIGEST" = "$CURRENT_DIGEST" ]; then
            echo "No update needed."
            echo "updated=false" >> $GITHUB_OUTPUT
          else
            echo "Image updated or first time run. Pushing to ECR..."
            docker tag $LOCAL_TAG ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:$IMAGE_TAG
            docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:$IMAGE_TAG
            echo $CURRENT_DIGEST > alpine-version.txt
            echo "updated=true" >> $GITHUB_OUTPUT
          fi
        env:
          PREVIOUS_DIGEST: ${{ env.PREVIOUS_DIGEST }}

      - name: Upload digest for future runs
        if: steps.push-image.outputs.updated == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: node-alpine-version
          path: alpine-version.txt
