name: Get Node Alpine Digest and Upload

on:
  workflow_dispatch:

jobs:
  fetch-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch node:alpine digest from Docker Hub
        run: |
          mkdir -p output
          curl -s -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
            https://registry-1.docker.io/v2/library/node/manifests/alpine \
            | jq -r '.config.digest' > output/node-alpine-digest.txt
          echo "Digest stored in output/node-alpine-digest.txt"

      - name: Upload digest as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-alpine-digest
          path: output/node-alpine-digest.txt
