name: Test Sync Node Alpine OIDC Workflow

on:
  workflow_dispatch:
  workflow_call:
    inputs:
     account-id:
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  test-sync:
    uses: ./.github/workflows/main.yml
    with:
       account-id: ${{ inputs.account-id }}


