name: Top-most-level

on:
  workflow_dispatch:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  test-sync:
    uses: ./.github/workflows/test_sync_node.yml
    with:
      account-id: ${{ inputs.account-id || '676206900064' }}
